import type { CategoryId } from "../types";
import { detectCategory } from "./agentEngine";
import { compileModIntent, type ModIntentSpec } from "./modIntentCompiler";
export interface ConversationContext{modIdea:string;category:CategoryId|null;keyFeatures:string[];decisions:Record<string,string>;refinements:string[];currentFocus:string|null;intentSpec:ModIntentSpec|null;}
export interface ConversationState{context:ConversationContext;conversationPhase:"exploring"|"refining"|"ready";lastTopic:string|null;}
export function createInitialContext():ConversationContext{return{modIdea:"",category:null,keyFeatures:[],decisions:{},refinements:[],currentFocus:null,intentSpec:null};}
function mergeIdea(current:string,input:string):string{const clean=input.trim();if(!current)return clean;if(current.toLowerCase().includes(clean.toLowerCase()))return current;return`${current}\nRefinement: ${clean}`;}
export function updateContext(context:ConversationContext,userInput:string,_agentResponse?:string):ConversationContext{const updated:ConversationContext={...context,decisions:{...context.decisions},refinements:[...context.refinements],keyFeatures:[...context.keyFeatures]};if(!updated.category)updated.category=detectCategory(userInput).id;const lower=userInput.toLowerCase();if(lower.includes("yes")||lower.includes("yeah")||lower.includes("sure")){if(updated.currentFocus)updated.decisions[updated.currentFocus]="approved";}if(lower.includes("no")||lower.includes("nah")||lower.includes("skip")){if(updated.currentFocus)updated.decisions[updated.currentFocus]="rejected";}updated.modIdea=mergeIdea(updated.modIdea,userInput);updated.refinements.push(userInput);updated.intentSpec=compileModIntent(updated.modIdea);updated.keyFeatures=[...new Set(updated.intentSpec.effects.flatMap(e=>e.matches.slice(0,3).map(m=>m.capability.id)))];updated.currentFocus=updated.intentSpec.missingInputs[0]??(updated.intentSpec.readiness==="NEEDS_VERIFICATION"?"verification":null);return updated;}
function bindingSummary(spec:ModIntentSpec):string{const ids=[...new Set(spec.effects.flatMap(e=>e.matches.slice(0,2).map(m=>m.capability.id)))];return ids.length?ids.join(" · "):"no verified binding yet";}
export function generateConversationalResponse(context:ConversationContext,_userInput:string,_phase:"exploring"|"refining"|"ready"):string{const spec=context.intentSpec;if(!spec)return"Describe the football behavior or asset you want changed. I’ll map it to a source-backed game surface before proposing a build.";if(spec.readiness==="BLOCKED"){const why=spec.effects.find(e=>e.disposition==="BLOCKED")?.reason??"The requested effect is not source-backed for this title.";return`I can map the request, but I will not label it buildable yet. ${why} Current bindings: ${bindingSummary(spec)}.`;}if(spec.readiness==="NEEDS_VERIFICATION")return`The request resolves to ${bindingSummary(spec)}, but at least one effect still requires a controlled game/runtime experiment. I can generate the exact experiment/build package now; it will remain ARTIFACT_NOT_BUILT / RUNTIME_NOT_RUN until real verification evidence is attached.`;if(spec.readiness==="NEEDS_INPUT"){const need=spec.missingInputs[0];const quick=spec.quickReplies.length?` Quick replies: ${spec.quickReplies.join(" | ")}.`:"";return`The source route is resolved (${bindingSummary(spec)}). I only need the next material input: ${need}.${quick}`;}return`Source route resolved: ${bindingSummary(spec)}. The intent is READY_TO_BUILD as an evidence-gated execution package. That means the recipe and proof gates are ready; it does not claim the game artifact or runtime test has already run.`;}
export function shouldTransitionToRefining(context:ConversationContext):boolean{return Boolean(context.intentSpec&&context.intentSpec.readiness!=="READY_TO_BUILD");}
export function shouldTransitionToReady(context:ConversationContext):boolean{return context.intentSpec?.readiness==="READY_TO_BUILD";}
export function suggestNextStep(context:ConversationContext):string|null{const spec=context.intentSpec;if(!spec)return"Describe the exact change you want in the game";if(spec.readiness==="BLOCKED")return"Choose a capability with title-specific source evidence or provide a verified title/schema binding";if(spec.missingInputs.length)return`Provide ${spec.missingInputs[0]}`;if(spec.readiness==="NEEDS_VERIFICATION")return"Generate the controlled experiment package and capture exact-build runtime evidence";return"Generate the governed execution package";}
