export interface Feature {
  id: string;
  name: string;
  description: string;
  category: FeatureCategory;
  phase: number;
  priority: "critical" | "high" | "medium" | "low";
  effort: "xs" | "sm" | "md" | "lg" | "xl";
  impact: "low" | "medium" | "high" | "critical";
  status: "planned" | "in-progress" | "complete" | "deferred";
  dependencies: string[];
  estimatedHours: number;
  tags: string[];
}

export type FeatureCategory =
  | "code-gen"
  | "testing"
  | "mod-mgmt"
  | "ai"
  | "visual"
  | "advanced"
  | "collab"
  | "docs"
  | "perf"
  | "integration"
  | "polish"
  | "analytics"
  | "community"
  | "quick-wins";

export interface Phase {
  id: number;
  name: string;
  description: string;
  timeline: string;
  goal: string;
  features: string[];
}

export const PHASES: Phase[] = [
  {
    id: 1,
    name: "Foundation & Quick Wins",
    description: "Core UX improvements that provide immediate value with minimal effort",
    timeline: "Week 1-2",
    goal: "Establish solid foundation with essential UX patterns",
    features: ["kw-shortcuts", "toast-notif", "loading-states", "auto-save", "undo-redo", "empty-states", "confirm-dialogs"],
  },
  {
    id: 2,
    name: "Code Quality & Developer Experience",
    description: "Enhance code generation, validation, and editing experience",
    timeline: "Week 3-4",
    goal: "Professional-grade code editing and generation tools",
    features: ["syntax-validation", "code-formatting", "diff-viewer", "progress-indicators", "dark-light-theme", "better-animations", "search-filter"],
  },
  {
    id: 3,
    name: "Preview & Testing",
    description: "Visual preview, sandbox testing, and validation tools",
    timeline: "Week 5-7",
    goal: "See what mods do before shipping, catch issues early",
    features: ["live-preview", "auto-completion", "sandbox-testing", "perf-profiling", "conflict-detection", "mod-templates", "tags-categories", "favorites"],
  },
  {
    id: 4,
    name: "Platform & Marketplace",
    description: "Community features, sharing, and mod ecosystem",
    timeline: "Week 8-10",
    goal: "Build a thriving mod ecosystem with sharing capabilities",
    features: ["mod-marketplace", "dependency-tracking", "auto-updates", "backup-restore", "mod-collections", "batch-operations"],
  },
  {
    id: 5,
    name: "AI Intelligence",
    description: "Smarter AI assistant with predictive capabilities",
    timeline: "Week 11-13",
    goal: "AI that anticipates needs and learns from patterns",
    features: ["predictive-suggestions", "pattern-learning", "better-context", "voice-input", "multi-language"],
  },
  {
    id: 6,
    name: "Collaboration",
    description: "Team features for working together on mods",
    timeline: "Week 14-16",
    goal: "Enable teams to collaborate on mod development",
    features: ["team-workspaces", "comments-notes", "change-tracking", "review-system", "merge-conflicts"],
  },
  {
    id: 7,
    name: "Documentation & Help",
    description: "Comprehensive help system and learning resources",
    timeline: "Week 17-18",
    goal: "Users can learn and find help easily",
    features: ["interactive-tutorials", "better-tooltips", "faq-system", "changelog"],
  },
  {
    id: 8,
    name: "Performance & Reliability",
    description: "Optimize speed, stability, and resilience",
    timeline: "Week 19-20",
    goal: "Fast, reliable, crash-free experience",
    features: ["faster-compilation", "error-recovery", "offline-mode", "memory-optimization", "crash-recovery"],
  },
  {
    id: 9,
    name: "Integration & Extensibility",
    description: "Connect with external tools and extend functionality",
    timeline: "Week 21-23",
    goal: "Flexible platform that integrates with existing workflows",
    features: ["export-formats", "git-integration", "api-access", "plugin-system", "third-party"],
  },
  {
    id: 10,
    name: "Visual Polish",
    description: "Refine the visual experience with custom themes and animations",
    timeline: "Week 24-25",
    goal: "Delightful, polished visual experience",
    features: ["custom-themes", "icon-packs", "sound-effects", "micro-animations", "responsive-design"],
  },
  {
    id: 11,
    name: "Analytics & Insights",
    description: "Track usage, performance, and user behavior",
    timeline: "Week 26-27",
    goal: "Data-driven decisions and insights",
    features: ["usage-stats", "perf-metrics", "trend-analysis", "user-insights", "ab-testing"],
  },
  {
    id: 12,
    name: "Community & Social",
    description: "Build community features for modders",
    timeline: "Week 28-30",
    goal: "Vibrant community of modders sharing and collaborating",
    features: ["user-profiles", "leaderboards", "forums", "mod-ratings", "showcase"],
  },
];

export const FEATURES: Feature[] = [
  // Phase 1: Quick Wins
  {
    id: "kw-shortcuts",
    name: "Keyboard Shortcuts",
    description: "Add Ctrl+S for save, Ctrl+Z for undo, and other power-user shortcuts throughout the app",
    category: "quick-wins",
    phase: 1,
    priority: "high",
    effort: "sm",
    impact: "high",
    status: "planned",
    dependencies: [],
    estimatedHours: 4,
    tags: ["ux", "productivity", "accessibility"],
  },
  {
    id: "toast-notif",
    name: "Toast Notifications",
    description: "Non-intrusive success/error/info messages that appear briefly and auto-dismiss",
    category: "quick-wins",
    phase: 1,
    priority: "high",
    effort: "sm",
    impact: "medium",
    status: "planned",
    dependencies: [],
    estimatedHours: 3,
    tags: ["ux", "feedback"],
  },
  {
    id: "loading-states",
    name: "Better Loading States",
    description: "Skeleton screens and progressive loading instead of spinners for better perceived performance",
    category: "quick-wins",
    phase: 1,
    priority: "medium",
    effort: "sm",
    impact: "medium",
    status: "planned",
    dependencies: [],
    estimatedHours: 4,
    tags: ["ux", "performance"],
  },
  {
    id: "auto-save",
    name: "Auto-Save",
    description: "Automatically save work at regular intervals and on key actions to prevent data loss",
    category: "quick-wins",
    phase: 1,
    priority: "critical",
    effort: "sm",
    impact: "critical",
    status: "planned",
    dependencies: [],
    estimatedHours: 3,
    tags: ["reliability", "ux"],
  },
  {
    id: "undo-redo",
    name: "Undo/Redo",
    description: "Reverse recent actions with Ctrl+Z/Ctrl+Y across all editing contexts",
    category: "quick-wins",
    phase: 1,
    priority: "high",
    effort: "md",
    impact: "high",
    status: "planned",
    dependencies: ["auto-save"],
    estimatedHours: 8,
    tags: ["ux", "safety"],
  },
  {
    id: "empty-states",
    name: "Better Empty States",
    description: "Helpful messages, illustrations, and CTAs when no data is available",
    category: "quick-wins",
    phase: 1,
    priority: "medium",
    effort: "xs",
    impact: "medium",
    status: "planned",
    dependencies: [],
    estimatedHours: 2,
    tags: ["ux", "onboarding"],
  },
  {
    id: "confirm-dialogs",
    name: "Confirmation Dialogs",
    description: "Prevent accidental deletions and destructive actions with confirmation prompts",
    category: "quick-wins",
    phase: 1,
    priority: "high",
    effort: "xs",
    impact: "high",
    status: "planned",
    dependencies: [],
    estimatedHours: 2,
    tags: ["ux", "safety"],
  },

  // Phase 2: Code Quality
  {
    id: "syntax-validation",
    name: "Syntax Validation",
    description: "Real-time code validation with error highlighting, squiggly underlines, and inline error messages",
    category: "code-gen",
    phase: 2,
    priority: "critical",
    effort: "lg",
    impact: "critical",
    status: "planned",
    dependencies: ["kw-shortcuts"],
    estimatedHours: 16,
    tags: ["code-quality", "dx"],
  },
  {
    id: "code-formatting",
    name: "Code Formatting",
    description: "Auto-format generated and user-written code with consistent style, indentation, and alignment",
    category: "code-gen",
    phase: 2,
    priority: "medium",
    effort: "md",
    impact: "medium",
    status: "planned",
    dependencies: ["syntax-validation"],
    estimatedHours: 8,
    tags: ["code-quality", "dx"],
  },
  {
    id: "diff-viewer",
    name: "Diff Viewer",
    description: "Side-by-side and inline diff views showing exactly what changed between mod versions",
    category: "code-gen",
    phase: 2,
    priority: "high",
    effort: "lg",
    impact: "high",
    status: "planned",
    dependencies: ["syntax-validation"],
    estimatedHours: 12,
    tags: ["code-quality", "versioning"],
  },
  {
    id: "progress-indicators",
    name: "Progress Indicators",
    description: "Visual progress bars, step indicators, and status updates for long-running operations",
    category: "visual",
    phase: 2,
    priority: "high",
    effort: "sm",
    impact: "high",
    status: "planned",
    dependencies: ["loading-states"],
    estimatedHours: 4,
    tags: ["ux", "feedback"],
  },
  {
    id: "dark-light-theme",
    name: "Dark/Light Theme Toggle",
    description: "Toggle between dark and light color schemes with system preference detection",
    category: "visual",
    phase: 2,
    priority: "medium",
    effort: "md",
    impact: "medium",
    status: "planned",
    dependencies: [],
    estimatedHours: 8,
    tags: ["visual", "accessibility"],
  },
  {
    id: "better-animations",
    name: "Better Animations",
    description: "Smoother transitions, micro-interactions, and delightful motion throughout the app",
    category: "visual",
    phase: 2,
    priority: "low",
    effort: "md",
    impact: "medium",
    status: "planned",
    dependencies: ["dark-light-theme"],
    estimatedHours: 8,
    tags: ["visual", "polish"],
  },
  {
    id: "search-filter",
    name: "Enhanced Search & Filter",
    description: "Fuzzy search, faceted filtering, and saved searches across all mods and patterns",
    category: "advanced",
    phase: 2,
    priority: "high",
    effort: "md",
    impact: "high",
    status: "planned",
    dependencies: [],
    estimatedHours: 10,
    tags: ["ux", "productivity"],
  },

  // Phase 3: Preview & Testing
  {
    id: "live-preview",
    name: "Live Preview",
    description: "Visual representation showing what the mod does in real-time as code changes",
    category: "code-gen",
    phase: 3,
    priority: "critical",
    effort: "xl",
    impact: "critical",
    status: "planned",
    dependencies: ["syntax-validation", "code-formatting"],
    estimatedHours: 24,
    tags: ["preview", "dx"],
  },
  {
    id: "auto-completion",
    name: "Auto-Completion",
    description: "Intelligent code suggestions as you type based on context, patterns, and vault mods",
    category: "code-gen",
    phase: 3,
    priority: "high",
    effort: "xl",
    impact: "high",
    status: "planned",
    dependencies: ["syntax-validation"],
    estimatedHours: 20,
    tags: ["dx", "ai"],
  },
  {
    id: "sandbox-testing",
    name: "Sandbox Environment",
    description: "Test mods in a simulated game environment with visual feedback and logging",
    category: "testing",
    phase: 3,
    priority: "critical",
    effort: "xl",
    impact: "critical",
    status: "planned",
    dependencies: ["live-preview", "syntax-validation"],
    estimatedHours: 32,
    tags: ["testing", "validation"],
  },
  {
    id: "perf-profiling",
    name: "Performance Profiling",
    description: "Show CPU/memory impact of mods with visual charts and optimization suggestions",
    category: "testing",
    phase: 3,
    priority: "medium",
    effort: "lg",
    impact: "medium",
    status: "planned",
    dependencies: ["sandbox-testing"],
    estimatedHours: 16,
    tags: ["testing", "performance"],
  },
  {
    id: "conflict-detection",
    name: "Conflict Detection",
    description: "Automatically detect and warn about incompatible mods, hook conflicts, and schema issues",
    category: "testing",
    phase: 3,
    priority: "high",
    effort: "lg",
    impact: "high",
    status: "planned",
    dependencies: ["syntax-validation"],
    estimatedHours: 14,
    tags: ["testing", "safety"],
  },
  {
    id: "mod-templates",
    name: "Mod Templates",
    description: "Pre-built mod templates for common use cases like recruiting, weather, playbook, etc.",
    category: "advanced",
    phase: 3,
    priority: "high",
    effort: "md",
    impact: "high",
    status: "planned",
    dependencies: [],
    estimatedHours: 10,
    tags: ["productivity", "onboarding"],
  },
  {
    id: "tags-categories",
    name: "Tags & Categories",
    description: "Organize mods with custom tags, categories, and smart grouping",
    category: "advanced",
    phase: 3,
    priority: "medium",
    effort: "sm",
    impact: "medium",
    status: "planned",
    dependencies: ["search-filter"],
    estimatedHours: 6,
    tags: ["organization", "ux"],
  },
  {
    id: "favorites",
    name: "Favorites & Bookmarks",
    description: "Bookmark frequently used mods, patterns, and features for quick access",
    category: "advanced",
    phase: 3,
    priority: "low",
    effort: "xs",
    impact: "medium",
    status: "planned",
    dependencies: ["tags-categories"],
    estimatedHours: 3,
    tags: ["ux", "productivity"],
  },

  // Phase 4: Platform
  {
    id: "mod-marketplace",
    name: "Mod Marketplace",
    description: "Browse, share, download, and rate mods from the community",
    category: "mod-mgmt",
    phase: 4,
    priority: "high",
    effort: "xl",
    impact: "critical",
    status: "planned",
    dependencies: ["mod-collections", "tags-categories"],
    estimatedHours: 30,
    tags: ["community", "sharing"],
  },
  {
    id: "dependency-tracking",
    name: "Dependency Tracking",
    description: "Visual dependency graph showing which mods depend on others and pattern relationships",
    category: "mod-mgmt",
    phase: 4,
    priority: "high",
    effort: "lg",
    impact: "high",
    status: "planned",
    dependencies: ["mod-marketplace"],
    estimatedHours: 14,
    tags: ["mod-mgmt", "visualization"],
  },
  {
    id: "auto-updates",
    name: "Auto-Updates",
    description: "Notify when mods have new versions with changelog and one-click update",
    category: "mod-mgmt",
    phase: 4,
    priority: "medium",
    effort: "lg",
    impact: "medium",
    status: "planned",
    dependencies: ["mod-marketplace"],
    estimatedHours: 12,
    tags: ["mod-mgmt", "ux"],
  },
  {
    id: "backup-restore",
    name: "Backup & Restore",
    description: "Cloud sync for all mods, sessions, and settings with versioned backups",
    category: "mod-mgmt",
    phase: 4,
    priority: "high",
    effort: "lg",
    impact: "high",
    status: "planned",
    dependencies: ["auto-save"],
    estimatedHours: 14,
    tags: ["reliability", "data"],
  },
  {
    id: "mod-collections",
    name: "Mod Collections",
    description: "Group related mods together into curated collections with descriptions",
    category: "mod-mgmt",
    phase: 4,
    priority: "medium",
    effort: "md",
    impact: "medium",
    status: "planned",
    dependencies: ["tags-categories"],
    estimatedHours: 8,
    tags: ["organization", "sharing"],
  },
  {
    id: "batch-operations",
    name: "Batch Operations",
    description: "Apply changes, export, or test multiple mods at once",
    category: "advanced",
    phase: 4,
    priority: "medium",
    effort: "md",
    impact: "medium",
    status: "planned",
    dependencies: ["mod-collections"],
    estimatedHours: 8,
    tags: ["productivity", "mod-mgmt"],
  },

  // Phase 5: AI Intelligence
  {
    id: "predictive-suggestions",
    name: "Predictive Suggestions",
    description: "AI anticipates what you want to add next based on context and patterns",
    category: "ai",
    phase: 5,
    priority: "high",
    effort: "xl",
    impact: "high",
    status: "planned",
    dependencies: ["auto-completion", "pattern-learning"],
    estimatedHours: 24,
    tags: ["ai", "productivity"],
  },
  {
    id: "pattern-learning",
    name: "Learning from Patterns",
    description: "AI improves suggestions based on your history, preferences, and successful mods",
    category: "ai",
    phase: 5,
    priority: "high",
    effort: "xl",
    impact: "high",
    status: "planned",
    dependencies: [],
    estimatedHours: 20,
    tags: ["ai", "intelligence"],
  },
  {
    id: "better-context",
    name: "Better Context Understanding",
    description: "AI understands complex mod requirements, multi-feature mods, and nuanced requests",
    category: "ai",
    phase: 5,
    priority: "critical",
    effort: "xl",
    impact: "critical",
    status: "planned",
    dependencies: ["pattern-learning"],
    estimatedHours: 28,
    tags: ["ai", "conversation"],
  },
  {
    id: "voice-input",
    name: "Voice Input",
    description: "Speak your mod ideas naturally using speech-to-text with context awareness",
    category: "ai",
    phase: 5,
    priority: "medium",
    effort: "lg",
    impact: "medium",
    status: "planned",
    dependencies: ["better-context"],
    estimatedHours: 14,
    tags: ["ai", "accessibility"],
  },
  {
    id: "multi-language",
    name: "Multi-Language Support",
    description: "Generate mods in different programming languages (Lua, Python, JavaScript, etc.)",
    category: "ai",
    phase: 5,
    priority: "low",
    effort: "xl",
    impact: "medium",
    status: "planned",
    dependencies: ["syntax-validation", "code-formatting"],
    estimatedHours: 24,
    tags: ["ai", "extensibility"],
  },

  // Phase 6: Collaboration
  {
    id: "team-workspaces",
    name: "Team Workspaces",
    description: "Share mods with team members with role-based access control",
    category: "collab",
    phase: 6,
    priority: "high",
    effort: "xl",
    impact: "high",
    status: "planned",
    dependencies: ["backup-restore"],
    estimatedHours: 28,
    tags: ["collab", "sharing"],
  },
  {
    id: "comments-notes",
    name: "Comments & Notes",
    description: "Add notes to mods for reference, TODOs, and documentation",
    category: "collab",
    phase: 6,
    priority: "medium",
    effort: "md",
    impact: "medium",
    status: "planned",
    dependencies: [],
    estimatedHours: 8,
    tags: ["collab", "documentation"],
  },
  {
    id: "change-tracking",
    name: "Change Tracking",
    description: "See who changed what and when with full audit trail",
    category: "collab",
    phase: 6,
    priority: "high",
    effort: "lg",
    impact: "high",
    status: "planned",
    dependencies: ["diff-viewer", "team-workspaces"],
    estimatedHours: 14,
    tags: ["collab", "versioning"],
  },
  {
    id: "review-system",
    name: "Review System",
    description: "Request reviews from others with inline comments and approval workflow",
    category: "collab",
    phase: 6,
    priority: "medium",
    effort: "lg",
    impact: "medium",
    status: "planned",
    dependencies: ["team-workspaces", "comments-notes"],
    estimatedHours: 16,
    tags: ["collab", "workflow"],
  },
  {
    id: "merge-conflicts",
    name: "Merge Conflict Resolution",
    description: "Handle conflicting changes with visual merge tools and conflict resolution",
    category: "collab",
    phase: 6,
    priority: "high",
    effort: "xl",
    impact: "high",
    status: "planned",
    dependencies: ["diff-viewer", "change-tracking"],
    estimatedHours: 20,
    tags: ["collab", "versioning"],
  },

  // Phase 7: Documentation
  {
    id: "interactive-tutorials",
    name: "Interactive Tutorials",
    description: "Step-by-step guided learning with hands-on exercises and progress tracking",
    category: "docs",
    phase: 7,
    priority: "high",
    effort: "xl",
    impact: "high",
    status: "planned",
    dependencies: [],
    estimatedHours: 24,
    tags: ["docs", "onboarding"],
  },
  {
    id: "better-tooltips",
    name: "Context-Sensitive Tooltips",
    description: "Helpful tooltips that appear contextually with explanations and examples",
    category: "docs",
    phase: 7,
    priority: "medium",
    effort: "md",
    impact: "medium",
    status: "planned",
    dependencies: [],
    estimatedHours: 8,
    tags: ["docs", "ux"],
  },
  {
    id: "faq-system",
    name: "FAQ System",
    description: "Searchable FAQ with common questions, answers, and video explanations",
    category: "docs",
    phase: 7,
    priority: "medium",
    effort: "md",
    impact: "medium",
    status: "planned",
    dependencies: ["search-filter"],
    estimatedHours: 8,
    tags: ["docs", "support"],
  },
  {
    id: "changelog",
    name: "Changelog & Release Notes",
    description: "Track what's new in each version with detailed release notes",
    category: "docs",
    phase: 7,
    priority: "low",
    effort: "sm",
    impact: "low",
    status: "planned",
    dependencies: [],
    estimatedHours: 4,
    tags: ["docs", "transparency"],
  },

  // Phase 8: Performance
  {
    id: "faster-compilation",
    name: "Faster Compilation",
    description: "Optimize code generation speed with caching, parallel processing, and lazy loading",
    category: "perf",
    phase: 8,
    priority: "high",
    effort: "lg",
    impact: "high",
    status: "planned",
    dependencies: ["syntax-validation"],
    estimatedHours: 16,
    tags: ["performance", "optimization"],
  },
  {
    id: "error-recovery",
    name: "Better Error Recovery",
    description: "Graceful handling of failures with auto-retry, fallbacks, and clear error messages",
    category: "perf",
    phase: 8,
    priority: "high",
    effort: "md",
    impact: "high",
    status: "planned",
    dependencies: ["toast-notif"],
    estimatedHours: 10,
    tags: ["reliability", "ux"],
  },
  {
    id: "offline-mode",
    name: "Offline Mode",
    description: "Work without internet connection with local-first architecture and sync on reconnect",
    category: "perf",
    phase: 8,
    priority: "medium",
    effort: "xl",
    impact: "medium",
    status: "planned",
    dependencies: ["auto-save", "backup-restore"],
    estimatedHours: 24,
    tags: ["reliability", "offline"],
  },
  {
    id: "memory-optimization",
    name: "Memory Optimization",
    description: "Reduce resource usage with virtualization, lazy loading, and efficient data structures",
    category: "perf",
    phase: 8,
    priority: "medium",
    effort: "lg",
    impact: "medium",
    status: "planned",
    dependencies: [],
    estimatedHours: 12,
    tags: ["performance", "optimization"],
  },
  {
    id: "crash-recovery",
    name: "Crash Recovery",
    description: "Auto-save and restore work after crashes with session recovery and data integrity",
    category: "perf",
    phase: 8,
    priority: "critical",
    effort: "md",
    impact: "critical",
    status: "planned",
    dependencies: ["auto-save"],
    estimatedHours: 10,
    tags: ["reliability", "safety"],
  },

  // Phase 9: Integration
  {
    id: "export-formats",
    name: "Multiple Export Formats",
    description: "Export mods in JSON, XML, YAML, and custom formats for different use cases",
    category: "integration",
    phase: 9,
    priority: "medium",
    effort: "md",
    impact: "medium",
    status: "planned",
    dependencies: [],
    estimatedHours: 8,
    tags: ["integration", "export"],
  },
  {
    id: "git-integration",
    name: "Git Integration",
    description: "Version control with Git for mods including commits, branches, and push/pull",
    category: "integration",
    phase: 9,
    priority: "high",
    effort: "xl",
    impact: "high",
    status: "planned",
    dependencies: ["diff-viewer", "change-tracking"],
    estimatedHours: 24,
    tags: ["integration", "versioning"],
  },
  {
    id: "api-access",
    name: "API Access",
    description: "Programmatic access to mod data with REST API and webhooks",
    category: "integration",
    phase: 9,
    priority: "medium",
    effort: "xl",
    impact: "medium",
    status: "planned",
    dependencies: [],
    estimatedHours: 20,
    tags: ["integration", "api"],
  },
  {
    id: "plugin-system",
    name: "Plugin System",
    description: "Extend functionality with plugins for custom tools, integrations, and features",
    category: "integration",
    phase: 9,
    priority: "high",
    effort: "xl",
    impact: "critical",
    status: "planned",
    dependencies: ["api-access"],
    estimatedHours: 28,
    tags: ["integration", "extensibility"],
  },
  {
    id: "third-party",
    name: "Third-Party Integrations",
    description: "Connect to Discord, Slack, GitHub, and other tools for workflow integration",
    category: "integration",
    phase: 9,
    priority: "low",
    effort: "lg",
    impact: "medium",
    status: "planned",
    dependencies: ["api-access", "plugin-system"],
    estimatedHours: 16,
    tags: ["integration", "workflow"],
  },

  // Phase 10: Visual Polish
  {
    id: "custom-themes",
    name: "Custom Themes",
    description: "Create your own color schemes with theme editor and preset gallery",
    category: "polish",
    phase: 10,
    priority: "medium",
    effort: "lg",
    impact: "medium",
    status: "planned",
    dependencies: ["dark-light-theme"],
    estimatedHours: 14,
    tags: ["visual", "customization"],
  },
  {
    id: "icon-packs",
    name: "Icon Packs",
    description: "Different icon styles (outlined, filled, rounded) for personalization",
    category: "polish",
    phase: 10,
    priority: "low",
    effort: "md",
    impact: "low",
    status: "planned",
    dependencies: [],
    estimatedHours: 6,
    tags: ["visual", "customization"],
  },
  {
    id: "sound-effects",
    name: "Sound Effects",
    description: "Audio feedback for actions with customizable sounds and volume control",
    category: "polish",
    phase: 10,
    priority: "low",
    effort: "md",
    impact: "low",
    status: "planned",
    dependencies: [],
    estimatedHours: 6,
    tags: ["audio", "feedback"],
  },
  {
    id: "micro-animations",
    name: "Micro-Animations",
    description: "Small delightful animations for button clicks, hovers, and state changes",
    category: "polish",
    phase: 10,
    priority: "low",
    effort: "md",
    impact: "medium",
    status: "planned",
    dependencies: ["better-animations"],
    estimatedHours: 8,
    tags: ["visual", "delight"],
  },
  {
    id: "responsive-design",
    name: "Responsive Design",
    description: "Better mobile and tablet experience with adaptive layouts and touch gestures",
    category: "polish",
    phase: 10,
    priority: "high",
    effort: "xl",
    impact: "high",
    status: "planned",
    dependencies: [],
    estimatedHours: 20,
    tags: ["visual", "mobile"],
  },

  // Phase 11: Analytics
  {
    id: "usage-stats",
    name: "Usage Statistics",
    description: "Track your modding patterns, time spent, and productivity metrics",
    category: "analytics",
    phase: 11,
    priority: "medium",
    effort: "lg",
    impact: "medium",
    status: "planned",
    dependencies: [],
    estimatedHours: 12,
    tags: ["analytics", "insights"],
  },
  {
    id: "perf-metrics",
    name: "Performance Metrics",
    description: "Measure mod performance with benchmarks and optimization recommendations",
    category: "analytics",
    phase: 11,
    priority: "medium",
    effort: "lg",
    impact: "medium",
    status: "planned",
    dependencies: ["perf-profiling"],
    estimatedHours: 14,
    tags: ["analytics", "performance"],
  },
  {
    id: "trend-analysis",
    name: "Trend Analysis",
    description: "See what's popular in the community with trending mods and patterns",
    category: "analytics",
    phase: 11,
    priority: "low",
    effort: "md",
    impact: "medium",
    status: "planned",
    dependencies: ["mod-marketplace"],
    estimatedHours: 10,
    tags: ["analytics", "community"],
  },
  {
    id: "user-insights",
    name: "User Insights",
    description: "Understand user behavior with heatmaps, flow analysis, and engagement metrics",
    category: "analytics",
    phase: 11,
    priority: "low",
    effort: "lg",
    impact: "medium",
    status: "planned",
    dependencies: ["usage-stats"],
    estimatedHours: 14,
    tags: ["analytics", "ux"],
  },
  {
    id: "ab-testing",
    name: "A/B Testing",
    description: "Test different approaches and measure which works better for users",
    category: "analytics",
    phase: 11,
    priority: "low",
    effort: "xl",
    impact: "medium",
    status: "planned",
    dependencies: ["user-insights"],
    estimatedHours: 20,
    tags: ["analytics", "optimization"],
  },

  // Phase 12: Community
  {
    id: "user-profiles",
    name: "User Profiles",
    description: "Share your modding history, achievements, and favorite mods",
    category: "community",
    phase: 12,
    priority: "medium",
    effort: "lg",
    impact: "medium",
    status: "planned",
    dependencies: ["team-workspaces"],
    estimatedHours: 14,
    tags: ["community", "social"],
  },
  {
    id: "leaderboards",
    name: "Leaderboards",
    description: "Top modders and mods with rankings, badges, and achievements",
    category: "community",
    phase: 12,
    priority: "low",
    effort: "md",
    impact: "medium",
    status: "planned",
    dependencies: ["user-profiles"],
    estimatedHours: 10,
    tags: ["community", "gamification"],
  },
  {
    id: "forums",
    name: "Discussion Forums",
    description: "Community forums for discussing mods, sharing tips, and getting help",
    category: "community",
    phase: 12,
    priority: "medium",
    effort: "xl",
    impact: "high",
    status: "planned",
    dependencies: ["user-profiles"],
    estimatedHours: 24,
    tags: ["community", "support"],
  },
  {
    id: "mod-ratings",
    name: "Mod Ratings & Reviews",
    description: "Community voting and detailed reviews for mods with helpfulness scores",
    category: "community",
    phase: 12,
    priority: "high",
    effort: "lg",
    impact: "high",
    status: "planned",
    dependencies: ["mod-marketplace"],
    estimatedHours: 14,
    tags: ["community", "quality"],
  },
  {
    id: "showcase",
    name: "Featured Mod Showcase",
    description: "Gallery of featured mods with spotlights, interviews, and highlights",
    category: "community",
    phase: 12,
    priority: "medium",
    effort: "md",
    impact: "medium",
    status: "planned",
    dependencies: ["mod-ratings", "mod-marketplace"],
    estimatedHours: 10,
    tags: ["community", "discovery"],
  },
];

export function getFeaturesByPhase(phaseId: number): Feature[] {
  return FEATURES.filter((f) => f.phase === phaseId);
}

export function getFeaturesByCategory(category: FeatureCategory): Feature[] {
  return FEATURES.filter((f) => f.category === category);
}

export function getPhaseProgress(phaseId: number): number {
  const features = getFeaturesByPhase(phaseId);
  if (features.length === 0) return 0;
  const completed = features.filter((f) => f.status === "complete").length;
  return Math.round((completed / features.length) * 100);
}

export function getTotalProgress(): number {
  if (FEATURES.length === 0) return 0;
  const completed = FEATURES.filter((f) => f.status === "complete").length;
  return Math.round((completed / FEATURES.length) * 100);
}

export function getTotalEstimatedHours(): number {
  return FEATURES.reduce((sum, f) => sum + f.estimatedHours, 0);
}

export function getRemainingHours(): number {
  return FEATURES.filter((f) => f.status !== "complete").reduce((sum, f) => sum + f.estimatedHours, 0);
}

export const CATEGORY_LABELS: Record<FeatureCategory, string> = {
  "code-gen": "Code Generation",
  testing: "Testing & Validation",
  "mod-mgmt": "Mod Management",
  ai: "AI Assistant",
  visual: "Visual Improvements",
  advanced: "Advanced Features",
  collab: "Collaboration",
  docs: "Documentation",
  perf: "Performance",
  integration: "Integration",
  polish: "Visual Polish",
  analytics: "Analytics",
  community: "Community",
  "quick-wins": "Quick Wins",
};
