import assert from "node:assert/strict";
import { PILE_LEAP_EXP001, LUA_HOOK_CERTIFIED_BUILDS } from "../.gauntlet-build/data/gameplayExperimentCatalog.js";
import { assessPileLeapReadiness, runtimeBuildCertified, summarizeObservation, promoteEvidence, buildPileLeapRunbook } from "../.gauntlet-build/lib/gameplayExperimentLab.js";
import { compileModIntent } from "../.gauntlet-build/lib/modIntentCompiler.js";
assert.equal(PILE_LEAP_EXP001.id,"CFB27-GAMEPLAY-EXP-001-PILE-LEAP");
assert.equal(PILE_LEAP_EXP001.components.find(c=>c.id==="character-gameplay-negative")?.evidence,"NEGATIVE_EVIDENCE");
assert(PILE_LEAP_EXP001.conditions.some(c=>c.id==="C0")&&PILE_LEAP_EXP001.conditions.some(c=>c.id==="C7"));
const pile=compileModIntent("CFB27: make my safety leap over a blocker pile for a tackle with more airborne reach and root motion");
const primary=pile.effects.flatMap(e=>e.matches.slice(0,1).map(m=>m.capability.id));
assert(primary.includes("FTC-ANIM-TARGET")||primary.includes("RUNTIME-INSTRUMENT"));
assert(!primary.includes("PLYR-ANIM-TRIPLE"),"defensive pile-leap must not primarily route to throw/run/carry CharacterGameplay styles");
const july=LUA_HOOK_CERTIFIED_BUILDS[0].sha256;
assert(runtimeBuildCertified(july));
assert(!runtimeBuildCertified("DEADBEEF"));
const current=assessPileLeapReadiness({offline:true,assetInventoryReady:false,baselineTrials:0,captureFps:60});
assert.equal(current.status,"READY_ASSET_DISCOVERY");
assert.equal(current.runtimeCertified,false);
const assetReady=assessPileLeapReadiness({offline:true,assetInventoryReady:true,baselineTrials:24,captureFps:60});
assert.equal(assetReady.status,"READY_ASSET_EXPERIMENT");
const certified=assessPileLeapReadiness({offline:true,exeSha256:july,assetInventoryReady:true,baselineTrials:24,captureFps:60});
assert.equal(certified.status,"READY_RUNTIME");
const s=summarizeObservation({condition:"C0",attempts:20,branchOccurrences:4,tackleSuccesses:3,blockerStops:12});
assert.equal(s.branchRate,0.2); assert.equal(s.tackleSuccessRate,0.15); assert.equal(s.blockerStopRate,0.6);
assert.equal(promoteEvidence({current:"TARGET",artifactRoundTrip:true,runtimeObserved:false,replicatedRuns:0,effectObserved:false,contradictoryRegression:false}),"WRITE_PROVEN");
assert.equal(promoteEvidence({current:"WRITE_PROVEN",artifactRoundTrip:true,runtimeObserved:true,replicatedRuns:1,effectObserved:true,contradictoryRegression:false}),"RUNTIME_PROVEN");
assert.equal(promoteEvidence({current:"RUNTIME_PROVEN",artifactRoundTrip:true,runtimeObserved:true,replicatedRuns:2,effectObserved:true,contradictoryRegression:false}),"BEHAVIOR_PROVEN");
assert.equal(promoteEvidence({current:"RUNTIME_PROVEN",artifactRoundTrip:true,runtimeObserved:true,replicatedRuns:3,effectObserved:true,contradictoryRegression:true}),"RUNTIME_PROVEN");
assert(buildPileLeapRunbook().stopRules.length>=4);
console.log("GAMEPLAY_LAB_PASS");